### ISSUE TITLE
Define moods

### ISSUE THREAD

**Issue by padesso** [bobbythree/arpeggio-generator#2]
@bobbythree is to define the different moods (happy, sad, etc) and the associated chords.

**Comment by padesso** [comment]
Update the moods and chords on the wiki here before we start putting things into code: https://github.com/bobbythree/aprgeggio-generator/wiki/Moods-and-Chords

**Comment by bobbythree** [comment]
I chose chords for the 6 moods as a starting point. Note that chords/arpeggios will emote more or less accurately depending on how they are voiced.
