### ISSUE TITLE
Arpeggiator Prototype

### ISSUE THREAD

**Issue by padesso** [bobbythree/arpeggio-generator#3]
Create an arpeggiator that can play chords flexibly.

**Comment by padesso** [comment]
PR #4 submitted.

**Comment by bobbythree** [comment]
For the add9, add11 and add13 chords, these should be replaced with major9 major11 and major13 chords as just adding a 9, 11 or 13 is too big of a jump. Major 9 has the 1, 3, 5, 7 and 9. Major 11 has 1, 3, 5, 7, 9, and 11, major 13 has 1, 3, 5, 7, 9, 11 and 13.

**Comment by bobbythree** [comment]
It will may be easier to deal with the music language/computer language barrier if you make the chordIntervals start at 1 isntead of 0. that way the interval numbers will line up with the interval names in music theory., for example a major chord is 1, 3, 5 and the chordIntervalls names it as 0, 4, 7. It just makes it easier to reason about stuff while talking if they match

**Comment by padesso** [comment]
I can hear what you're saying when I play those but I'll need to talk it over to understand the changes.

**Comment by padesso** [comment]
Updated with what I think you mean and am sending a PR shortly.  Sounds more pleasant at least :)

**Comment by bobbythree** [comment]
Made one change, adding [17] interval to major13 chord and push to main

**Comment by padesso** [comment]
Sync'd my fork to yours.  Anything else on this or we going to close and move along?

**Comment by bobbythree** [comment]
As a prototype I’d say it’s done. I think we will tweak some of the chords or add chords  later when we know more of exactly what we want

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bobbythree** [comment]
prototype complete
